const mydate = new Date()
//console.log(mydate.getTime())
// console.log(mydate.toLocaleString('en-US', {timeZone: 'Asia/Kolkata'}))
// console.log(mydate.toLocaleDateString())
// console.log(mydate.toLocaleTimeString())
// console.log(mydate.getFullYear())
// console.log(mydate.getMonth())
// console.log(mydate.getDate())
// console.log(mydate.getDay())
// console.log(mydate.getHours())
// console.log(mydate.getMinutes())
// console.log(mydate.getSeconds())
// console.log(mydate.getMilliseconds())
// console.log(mydate.getTimezoneOffset()) 
// console.log(mydate)
console.log(mydate.toISOString())
console.log(mydate.toUTCString())
console.log(mydate.toJSON())
console.log(mydate.getUTCFullYear())
console.log(mydate.getUTCHours())
